### ISSUE TITLE
Build failure of odroidc2-v2015.01 after 61f29b

### ISSUE THREAD

**Issue by asavah** [hardkernel/u-boot#27]
Build fails after https://github.com/hardkernel/u-boot/commit/61f29bb518e28ed69d94e87c5f5c8cabe001ec5a

```
  OBJCOPY u-boot.hex
    CPP user_task.lds
aarch64-none-elf-cpp: error: unrecognized command line option '-mthumb'
aarch64-none-elf-cpp: error: unrecognized command line option '-mno-sched-prolog'
Makefile:108: recipe for target '/home/asavah/kross/src/uboot/hardkernel/build/scp_task/user_task.lds' failed
```

Do these commits get tested before pushing?

**Comment by Kwiboo** [comment]
You will need `arm-none-eabi-gcc` to build `bl301.bin` after https://github.com/hardkernel/u-boot/commit/61f29bb518e28ed69d94e87c5f5c8cabe001ec5a, you should also move your `CROSS_COMPILE=aarch64-none-elf-` on the command line or export as an environment variable otherwise `make` will see it as an override variable and use wrong compiler when building `bl301.bin`.

See https://github.com/Kwiboo/LibreELEC.tv/commit/eda15042f6c449785230abc198fd7012257acf9f on how this can be done when building LibreELEC.

**Comment by asavah** [comment]
Thanks, did not notice that in the (new) Makefile itself,
is there any recommended version for arm-none-eabi- toolchain?

**Comment by bkrepo** [comment]
Pre-built bl301.bin binary was added agagin and created bl301 firmware source repository.
- bl301 repository: https://github.com/hardkernel/u-boot_firmware/tree/odroidc2-bl301

Please refer to [this link](http://odroid.com/dokuwiki/doku.php?id=en:c2_building_u-boot#how_to_build_u-boot_with_bl301_firmware).
